### PR TITLE
Literate-based documentation

### PR DESCRIPTION
**Pull request by gdalle**
**Main goals:**
- Create a new file `test/animals.jl` with
   - the code from the test suite
   - the additional comments from the README
- Include it in the test suite
- Include it in the documentation `docs/make.jl` with Literate.jl

**Other documentation changes:**
- Ignore `docs/Manifest.toml`
- Use README as documentation home page
- Activate PR docs preview
- Add action to clean up PR docs preview once closed

**Other test changes:**
- Add Aqua.jl to tests
- Add doctests to tests

### CODE REVIEW

**Comment by rafaqz** [comment]
+1 for adding Aqua. 

This is great bit I dont use literate like this, so cant give much of a review. I'll merge anything that passes tests ;)

**Comment by gdalle** [comment]
> +1 for adding Aqua.

The ambiguity test fails, I left it in case it is something you can fix.

> This is great but I dont use literate like this

How do you use it?

>  I'll merge anything that passes tests ;)

Gotta enable the workflows first (and as I said one Aqua test will fail).

You'll be able to see a docs preview at <https://rafaqz.github.io/Interfaces.jl/previews/PR17> once PR CI is done

**Comment by rafaqz** [comment]
For ambiguity we just need to define this function:
```julia
test(::Type{<:Interfaces.Interface{Keys}}, ::Type, ::Interfaces.TestObjectWrapper)
```

The `kwcall` version we will get for free with it.

I've only used Literate.jl for making jupyter notebooks from scripts.

**Comment by gdalle** [comment]
> For ambiguity we just need to define this function:

Can you maybe add that line? I'm not sure what to do with the `Keys`, `T` and `T1` in particular

> I've only used Literate.jl for making jupyter notebooks from scripts.

The principle here is the same, except that `Literate.markdown` turns a `.jl` with the Markdown in comments into a `.md` that can be parsed by Documenter

**Comment by gdalle** [comment]
@rafaqz the docs preview apparently doesn't work because I opened this PR from a fork (since I'm not a repo member). But I tested it locally and it looks good. Also merged the changes from #19 so it's ready to roll

**Pull request merged**
